name: Update Sitemap

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update XML Sitemap
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
        echo '<table border="1" cellspacing="0" cellpadding="4">' >> sitemap.xml
        echo '  <tr>' >> sitemap.xml
        echo '    <th>Commit Hash</th>' >> sitemap.xml
        echo '    <th>Commit Date</th>' >> sitemap.xml
        echo '  </tr>' >> sitemap.xml
        git log -n 10 --pretty=format:'  <tr>\n    <td><a href="https://github.com/Neutx/Portfolio/commit/%H">%h</a></td>\n    <td>%ad</td>\n  </tr>\n' --date=iso >> sitemap.xml
        echo '</table>' >> sitemap.xml

        git config user.name 'GitHub Actions'
        git config user.email 'dlprwz@gmail.com'
        git add sitemap.xml
        git commit -m "Update sitemap.xml"
        git push

      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
